//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.AuctionBids = new HashSet<AuctionBid>();
            this.AuctionConnections = new HashSet<AuctionConnection>();
            this.AuctionFavorites = new HashSet<AuctionFavorite>();
            this.AuctionPhotoes = new HashSet<AuctionPhoto>();
        }
    
        public int ID { get; set; }
        public int AutoID { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int StartPrice { get; set; }
        public int CurrentPrice { get; set; }
        public int PriceUSDSearch { get; set; }
        public int PriceUAHSearch { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<System.DateTime> DateStopped { get; set; }
        public System.DateTime Deadline { get; set; }
        public string CompletionJobID { get; set; }
        public string DeletionJobID { get; set; }
        public int Views { get; set; }
        public int StatusID { get; set; }
    
        public virtual AuctionStatu AuctionStatu { get; set; }
        public virtual Auto Auto { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionBid> AuctionBids { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionConnection> AuctionConnections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionFavorite> AuctionFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionPhoto> AuctionPhotoes { get; set; }
    }
}
