//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoExchange
    {
        public int ID { get; set; }
        public int TargetAutoID { get; set; }
        public int OfferedAutoID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> DiffPrice { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> DiffPriceDirection { get; set; }
    
        public virtual Auto AutoOffered { get; set; }
        public virtual Auto AutoTarget { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
