//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auto()
        {
            this.AutoExchangesOutcome = new HashSet<AutoExchange>();
            this.AutoExchangesIncome = new HashSet<AutoExchange>();
            this.AutoFavorites = new HashSet<AutoFavorite>();
            this.AutoPhotoes = new HashSet<AutoPhoto>();
            this.ContactsRequests = new HashSet<ContactsRequest>();
            this.AutoComforts = new HashSet<AutoComfort>();
            this.AutoMiscs = new HashSet<AutoMisc>();
            this.AutoMultimedias = new HashSet<AutoMultimedia>();
            this.AutoSecurities = new HashSet<AutoSecurity>();
            this.AutoStates = new HashSet<AutoState>();
            this.Auctions = new HashSet<Auction>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public Nullable<System.DateTime> DateExpires { get; set; }
        public Nullable<System.DateTime> DateAppearance { get; set; }
        public int StatusID { get; set; }
        public int RegionID { get; set; }
        public int TransportTypeID { get; set; }
        public int BodyTypeID { get; set; }
        public int MakeID { get; set; }
        public int ModelID { get; set; }
        public int YearOfIssue { get; set; }
        public string Modification { get; set; }
        public int TSRegistrationID { get; set; }
        public int Probeg { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> PriceUSD { get; set; }
        public Nullable<int> PriceUAH { get; set; }
        public int PriceUSDSearch { get; set; }
        public int PriceUAHSearch { get; set; }
        public bool IsTorgAvailable { get; set; }
        public bool IsExchangeAvailable { get; set; }
        public Nullable<int> TransmissionTypeID { get; set; }
        public Nullable<int> DriveTypeID { get; set; }
        public Nullable<int> NumberOfDoors { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
        public Nullable<int> ColorID { get; set; }
        public bool IsColorMetallic { get; set; }
        public Nullable<int> FuelTypeID { get; set; }
        public Nullable<decimal> FuelConsumptionCity { get; set; }
        public Nullable<decimal> FuelConsumptionHighway { get; set; }
        public Nullable<decimal> FuelConsumptionMixed { get; set; }
        public Nullable<decimal> EngineCapacity { get; set; }
        public Nullable<int> Power { get; set; }
        public string Description { get; set; }
        public int Views { get; set; }
        public string CompletionJobID { get; set; }
        public int Top { get; set; }
        public string PlaceLat { get; set; }
        public string PlaceLng { get; set; }
    
        public virtual AutoBodyType AutoBodyType { get; set; }
        public virtual AutoColor AutoColor { get; set; }
        public virtual AutoDriveType AutoDriveType { get; set; }
        public virtual AutoFuelType AutoFuelType { get; set; }
        public virtual AutoMake AutoMake { get; set; }
        public virtual AutoModel AutoModel { get; set; }
        public virtual AutoStatu AutoStatu { get; set; }
        public virtual AutoTransmissionType AutoTransmissionType { get; set; }
        public virtual AutoTransportType AutoTransportType { get; set; }
        public virtual AutoTSRegistration AutoTSRegistration { get; set; }
        public virtual City City { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoExchange> AutoExchangesOutcome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoExchange> AutoExchangesIncome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoFavorite> AutoFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoPhoto> AutoPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactsRequest> ContactsRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoComfort> AutoComforts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoMisc> AutoMiscs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoMultimedia> AutoMultimedias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoSecurity> AutoSecurities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoState> AutoStates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auction> Auctions { get; set; }
    }
}
