//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactsRequest
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> AutoID { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual User User { get; set; }
    }
}
