//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCarsEntities : DbContext
    {
        public XCarsEntities()
            : base("name=XCarsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuctionBid> AuctionBids { get; set; }
        public virtual DbSet<AuctionConnection> AuctionConnections { get; set; }
        public virtual DbSet<Auto> Autoes { get; set; }
        public virtual DbSet<AutoBodyType> AutoBodyTypes { get; set; }
        public virtual DbSet<AutoColor> AutoColors { get; set; }
        public virtual DbSet<AutoComfort> AutoComforts { get; set; }
        public virtual DbSet<AutoDriveType> AutoDriveTypes { get; set; }
        public virtual DbSet<AutoExchange> AutoExchanges { get; set; }
        public virtual DbSet<AutoFavorite> AutoFavorites { get; set; }
        public virtual DbSet<AutoFuelType> AutoFuelTypes { get; set; }
        public virtual DbSet<AutoMake> AutoMakes { get; set; }
        public virtual DbSet<AutoMisc> AutoMiscs { get; set; }
        public virtual DbSet<AutoModel> AutoModels { get; set; }
        public virtual DbSet<AutoMultimedia> AutoMultimedias { get; set; }
        public virtual DbSet<AutoPhoto> AutoPhotoes { get; set; }
        public virtual DbSet<AutoSecurity> AutoSecurities { get; set; }
        public virtual DbSet<AutoState> AutoStates { get; set; }
        public virtual DbSet<AutoStatu> AutoStatus { get; set; }
        public virtual DbSet<AutoTransmissionType> AutoTransmissionTypes { get; set; }
        public virtual DbSet<AutoTransportType> AutoTransportTypes { get; set; }
        public virtual DbSet<AutoTSRegistration> AutoTSRegistrations { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ContactsRequest> ContactsRequests { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PurchaseType> PurchaseTypes { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ScheduledEmail> ScheduledEmails { get; set; }
        public virtual DbSet<ScheduledEmailObjectType> ScheduledEmailObjectTypes { get; set; }
        public virtual DbSet<ScheduledEmailStatu> ScheduledEmailStatus { get; set; }
        public virtual DbSet<SiteSetting> SiteSettings { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionState> TransactionStates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserConnection> UserConnections { get; set; }
        public virtual DbSet<AuctionPhoto> AuctionPhotoes { get; set; }
        public virtual DbSet<AuctionFavorite> AuctionFavorites { get; set; }
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<AuctionStatu> AuctionStatus { get; set; }
    }
}
