//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string LMI_PAYMENT_NO { get; set; }
        public Nullable<int> LMI_PREREQUEST { get; set; }
        public int LMI_MERCHANT_ID { get; set; }
        public decimal LMI_PAYMENT_AMOUNT { get; set; }
        public int LMI_MODE { get; set; }
        public Nullable<System.DateTime> LMI_SYS_PAYMENT_DATE { get; set; }
        public string LMI_HASH { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> PurchaseTypeID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public bool IsOpen { get; set; }
        public decimal UsedFromBalance { get; set; }
    
        public virtual PurchaseType PurchaseType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
