//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledEmail
    {
        public int ID { get; set; }
        public System.DateTime DateScheduled { get; set; }
        public System.DateTime DateDue { get; set; }
        public int StatusID { get; set; }
        public string To { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int ObjectTypeID { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public System.DateTime DateEligible { get; set; }
    
        public virtual ScheduledEmailObjectType ScheduledEmailObjectType { get; set; }
        public virtual ScheduledEmailStatu ScheduledEmailStatu { get; set; }
    }
}
