//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int StateID { get; set; }
        public Nullable<int> PurchaseTypeID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public int LMI_MODE { get; set; }
        public string LMI_PAYMENT_SYSTEM { get; set; }
        public string LMI_PAYMENT_DESC { get; set; }
        public Nullable<int> LMI_SYS_PAYMENT_ID { get; set; }
        public Nullable<System.DateTime> LMI_SYS_PAYMENT_DATE { get; set; }
        public string LMI_PAYER_IDENTIFIER { get; set; }
    
        public virtual PurchaseType PurchaseType { get; set; }
        public virtual TransactionState TransactionState { get; set; }
        public virtual User User { get; set; }
    }
}
