CREATE TABLE [dbo].[Auto] (
    [ID]                     INT             IDENTITY (1, 1) NOT NULL,
    [UserID]                 INT             NOT NULL,
    [DateCreated]            DATETIME        NOT NULL,
    [DateUpdated]            DATETIME        NOT NULL,
    [DatePublished]          DATETIME        NULL,
    [DateExpires]            DATETIME        NULL,
    [DateAppearance]         DATETIME        NULL,
    [StatusID]               INT             CONSTRAINT [DF_Auto_StatusID] DEFAULT ((1)) NOT NULL,
    [RegionID]               INT             NOT NULL,
    [TransportTypeID]        INT             NOT NULL,
    [BodyTypeID]             INT             NOT NULL,
    [MakeID]                 INT             NOT NULL,
    [ModelID]                INT             NOT NULL,
    [YearOfIssue]            INT             NOT NULL,
    [Modification]           NVARCHAR (256)  NULL,
    [TSRegistrationID]       INT             NOT NULL,
    [Probeg]                 INT             NOT NULL,
    [CurrencyID]             INT             NOT NULL,
    [PriceUSD]               INT             NULL,
    [PriceUAH]               INT             NULL,
    [PriceUSDSearch]         INT             NOT NULL,
    [PriceUAHSearch]         INT             NOT NULL,
    [IsTorgAvailable]        BIT             NOT NULL,
    [IsExchangeAvailable]    BIT             NOT NULL,
    [TransmissionTypeID]     INT             NULL,
    [DriveTypeID]            INT             NULL,
    [NumberOfDoors]          INT             NULL,
    [NumberOfSeats]          INT             NULL,
    [ColorID]                INT             NULL,
    [IsColorMetallic]        BIT             NOT NULL,
    [FuelTypeID]             INT             NULL,
    [FuelConsumptionCity]    DECIMAL (18, 1) NULL,
    [FuelConsumptionHighway] DECIMAL (18, 1) NULL,
    [FuelConsumptionMixed]   DECIMAL (18, 1) NULL,
    [EngineCapacity]         DECIMAL (18, 1) NULL,
    [Power]                  DECIMAL (18, 1) NULL,
    [Description]            NVARCHAR (MAX)  NULL,
    [Views]                  INT             CONSTRAINT [DF_Auto_Views] DEFAULT ((0)) NOT NULL,
    [CompletionJobID]        NVARCHAR (50)   NULL,
    [Top]                    INT             CONSTRAINT [DF_Auto_Top] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Auto] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Auto_AutoBodyType] FOREIGN KEY ([BodyTypeID]) REFERENCES [dbo].[AutoBodyType] ([ID]),
    CONSTRAINT [FK_Auto_AutoColor] FOREIGN KEY ([ColorID]) REFERENCES [dbo].[AutoColor] ([ID]),
    CONSTRAINT [FK_Auto_AutoDriveType] FOREIGN KEY ([DriveTypeID]) REFERENCES [dbo].[AutoDriveType] ([ID]),
    CONSTRAINT [FK_Auto_AutoFuelType] FOREIGN KEY ([FuelTypeID]) REFERENCES [dbo].[AutoFuelType] ([ID]),
    CONSTRAINT [FK_Auto_AutoMake] FOREIGN KEY ([MakeID]) REFERENCES [dbo].[AutoMake] ([ID]),
    CONSTRAINT [FK_Auto_AutoModel] FOREIGN KEY ([ModelID]) REFERENCES [dbo].[AutoModel] ([ID]),
    CONSTRAINT [FK_Auto_AutoStatus] FOREIGN KEY ([StatusID]) REFERENCES [dbo].[AutoStatus] ([ID]),
    CONSTRAINT [FK_Auto_AutoTransmissionType] FOREIGN KEY ([TransmissionTypeID]) REFERENCES [dbo].[AutoTransmissionType] ([ID]),
    CONSTRAINT [FK_Auto_AutoTransportType] FOREIGN KEY ([TransportTypeID]) REFERENCES [dbo].[AutoTransportType] ([ID]),
    CONSTRAINT [FK_Auto_AutoTSRegistration] FOREIGN KEY ([TSRegistrationID]) REFERENCES [dbo].[AutoTSRegistration] ([ID]),
    CONSTRAINT [FK_Auto_City] FOREIGN KEY ([RegionID]) REFERENCES [dbo].[City] ([ID]),
    CONSTRAINT [FK_Auto_Currency] FOREIGN KEY ([CurrencyID]) REFERENCES [dbo].[Currency] ([ID]),
    CONSTRAINT [FK_Auto_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID])
);

